name: Deploy Artisan API

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/deployuser/server/artisan-api

            # Check if the repository is already cloned
            if [ -d ".git" ]; then
              # If already cloned, switch to the develop branch and pull latest changes
              git checkout develop
              git pull origin develop
            else
              # If not cloned yet, clone the repository
              git clone https://github.com/Fordsoft-Limited/artisan-api.git
              git checkout develop
            fi

            # Install dependencies and build the application
            npm install
            npm run build

            # Restart the application
            pm2 describe artisan-api > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart artisan-api
            else
              pm2 start dist/main.js --name artisan-api
            fi